-- Claim - Claim File Generation Body

with Ada.Text_IO;
with Ada.Calendar;
with Ada.Calendar.Formatting;
with Ada.Directories;

package body Claim is

   use Ada.Text_IO;

   procedure Generate (
      Claim_File  : in String;
      File_Path   : in String;
      Description : in String;
      License     : in String
   ) is
      File : File_Type;
      Now  : constant Ada.Calendar.Time := Ada.Calendar.Clock;
      Timestamp : constant String := Ada.Calendar.Formatting.Image (Now);
      File_Exists : constant Boolean := Ada.Directories.Exists (File_Path);
      File_Size : constant String :=
         (if File_Exists then
            Ada.Directories.Size (File_Path)'Image & " bytes"
         else
            "Unknown (file not found)");
   begin
      Create (File, Out_File, Claim_File);

      -- Write claim file in Markdown format
      Put_Line (File, "# Intellectual Property Claim");
      Put_Line (File, "");
      Put_Line (File, "## Claim Information");
      Put_Line (File, "");
      Put_Line (File, "- **Claimed Work**: " & File_Path);
      Put_Line (File, "- **Description**: " & Description);
      Put_Line (File, "- **License**: " & License);
      Put_Line (File, "- **Claim Date**: " & Timestamp);
      Put_Line (File, "- **File Size**: " & File_Size);
      Put_Line (File, "");
      Put_Line (File, "## Declaration");
      Put_Line (File, "");
      Put_Line (File, "This claim establishes provenance and ownership of the referenced");
      Put_Line (File, "intellectual property as of the timestamp above. This claim is");
      Put_Line (File, "cryptographically signed and blockchain-anchored for legal");
      Put_Line (File, "defensibility.");
      Put_Line (File, "");
      Put_Line (File, "## Timestamp Verification");
      Put_Line (File, "");
      Put_Line (File, "This claim has been timestamped using OpenTimestamps and anchored");
      Put_Line (File, "to the Bitcoin blockchain. The corresponding .ots file provides");
      Put_Line (File, "cryptographic proof of existence at the claimed time.");
      Put_Line (File, "");
      Put_Line (File, "To verify:");
      Put_Line (File, "```bash");
      Put_Line (File, "ots verify " & Claim_File & ".ots");
      Put_Line (File, "```");
      Put_Line (File, "");
      Put_Line (File, "## Cryptographic Signature");
      Put_Line (File, "");
      Put_Line (File, "This claim is signed with GPG. The signature file (.sig) and");
      Put_Line (File, "signed Git commits provide additional verification.");
      Put_Line (File, "");
      Put_Line (File, "To verify GPG signature:");
      Put_Line (File, "```bash");
      Put_Line (File, "gpg --verify " & Claim_File & ".sig " & Claim_File);
      Put_Line (File, "```");
      Put_Line (File, "");
      Put_Line (File, "## License Terms");
      Put_Line (File, "");
      Put_Line (File, "This work is released under the " & License & " license.");
      Put_Line (File, "");
      Put_Line (File, "---");
      Put_Line (File, "");
      Put_Line (File, "*Generated by Claim Forge v1.0.0*");

      Close (File);

   exception
      when others =>
         if Is_Open (File) then
            Close (File);
         end if;
         raise;
   end Generate;

end Claim;
